### ISSUE TITLE
Button is unresponsive after doneLoadingAnimation(int, Bitmap) is called.

### ISSUE THREAD

**Issue by CleverChuk** [leandroBorgesFerreira/LoadingButtonAndroid#157]
I'm not sure if this is a feature or a bug. Please advise.

**Comment by leandroBorgesFerreira** [comment]
Hello @CleverChuk. I'm sorry it took me so long to answer your question. 

Yes, this is the expected behaviour. You must call revert `revertAnimation()` if you need to keep using the button.

I don't see this as an issue in this library, so I'm closing this. If you still think this is a problem, fell free to reopen the issue.
