### ISSUE TITLE
Animation disappears on rotation

### ISSUE THREAD

**Issue by olga-perederieieva** [leandroBorgesFerreira/LoadingButtonAndroid#39]
If I rotate the screen while the button is in progress, the button completely disappears even though I call startAnimation straight after orientation change happened. When I try to debug startAnimation in that case, in the following code mParams.mInitialWidth = getWidth();
            mParams.mInitialHeight = getHeight(); 
getWidth() and getHeight() both return 0.
Should I do something special in order to make the button remember its state on orientation change?

**Comment by leandroBorgesFerreira** [comment]
Hi Olga. This happens because you are asking the button to animate before it draws itself in the screen, so it doesn't know it size yet. 

This is a bug in this view and I will correct this as soon as I can. As a work around you could wait a little bit before starting the animation in the screen like:

`Handler().post({ button.startAnimation() }, 50)`

Sorry for the inconvenience!

**Comment by alashow** [comment]
Any updates on this?

**Comment by leandroBorgesFerreira** [comment]
Not yet. I will try to find some time to solve this. But the work around will work meanwhile.

**Comment by MrStahlfelge** [comment]
Fixed it

**Comment by leandroBorgesFerreira** [comment]
This problem was solved by @MrStahlfelge. Thanks for the help!
